
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-spring
  labels:
    app: hello-spring

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: hello-spring
        tier: frontend

    spec:
      containers:
      - name: hello-spring
        # Replace [GCLOUD_PROJECT] with your project ID.
        image: gcr.io/fukudak-java/hello-spring

        imagePullPolicy: Always

        ports:
        - name: http-server
          containerPort: 8080