apiVersion: v1
kind: Service

metadata:
  name: hello-spring
  labels:
    app: hello-spring
    tier: frontend

spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: hello-spring
    tier: frontend
